### ISSUE TITLE
MagicOreGen : Upgrade generators by using money

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/MagicCobblestoneGenerator#1]
_From @Poslovitch on January 24, 2018 14:20_

*Splited from #130, originally created by @ItzAntony.*

Allow different types of ore generators, that way people can add upgrades to their generators for in-game money. This could be done in a GUI and once purchased it will change to Purchased. There should also be an option for generators to reset on island restart or not.

E.g 
**Tier 1 - 90% Cobblestone, 6% Coal, 4% Iron Ingot [$10,000]**
**Tier 2 - 75% Cobblestone, 8% Coal, 10% Iron Ingot, 8% Redstone, 4% Gold Ingot [$25,000]**

_Copied from original issue: BentoBoxWorld/bentobox#132_

**Comment by Awakened-Redstone** [comment]
Hmmm. I can make that, with a gui.
I'll use configs.  But,  IDK how to use SQL

**Comment by Joeripoes** [comment]
awakened make the cobble addon plz ty :)

**Comment by Awakened-Redstone** [comment]
I'll do it when I get time. I'm busy.
I need update FrameMiner before xD

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.
