### ISSUE TITLE
Tiers for upgrades

### ISSUE THREAD

**Issue by Drizzy-America** [BentoBoxWorld/MagicCobblestoneGenerator#101]
#### Is your feature request related to a problem?
I am looking for a way to make it so they can't just activate and deactivate generators cause it causes user end confusion. 

#### Describe the solution you'd like us to implement.
So, for the user end gui, it would be tiers that you upgrade if you choose to not have the activate/deactivation option. So the player can just progress through the tiers and avoid confusion on there end.

#### Describe alternatives you've considered.
I have thought about using BossShopPro for the GUI/User End panel, I just don't quite like doing that.

**Comment by Drizzy-America** [comment]
A side note on this it would be nice to separate other generators tiers (nether, end, main island).

**Comment by BONNe** [comment]
MCG was made on a premise to use something that does not exist in other stone generator addons. 

I do not see a point in copy-paste already existing stone generator plugins with a tier system. It does not introduce anything new. 

MCG is built so admins offer different available generators, and users choose which one to use. There is other generator plugins that have a tier system. I suggest using these plugins if you need a tier system.
