### ISSUE TITLE
Apply  MagicCobblestoneGenerator for spawn islands

### ISSUE THREAD

**Issue by Awakened-Redstone** [BentoBoxWorld/MagicCobblestoneGenerator#108]
### Is your feature request related to a problem?

The spawn island doesn't show on the database nor on admin panel GUI, considering this it seems to not work with the addon.

### Describe the solution you'd like.

Apply the addon functionalities for the spawn island, registering it as a special island.
Registering as a special island will allow changing the behavior on it (#107) and to show it differently on the admin pannel.

### Describe alternatives you've considered.

‎

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by BONNe** [comment]
You can always join the spawn island, change settings, and set it back as spawn island.

However, I agree, that allowing to change it via Admin Menu would be a much better approach.
