### ISSUE TITLE
Setting Flag to toggle on/off the Magic Cobblestone Generator 

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/MagicCobblestoneGenerator#11]
Hi.
#### Is your feature request related to a problem?
I need to enable and disable the generator easier.
Beacause today i change the file config but when i reloaded configuration, it creates lags.

#### Describe the solution you'd like us to implement.
Add one command to enable / disable the maggic cobblestone generator.

**Comment by kiwifrogg** [comment]
I second this, a way to toggle the special blocks off when ppl only want cobble would be handy.

**Comment by BONNe** [comment]
You can enable/disable generator via island flag in settings.

**Comment by Poslovitch** [comment]
I suppose the original request was to have an admin setting flag, but I will do it as a player settings flag - so that they can toggle on/off the Magic cobblestone generator.
