### ISSUE TITLE
I would like to add the function to generate ore when water and fence meet

### ISSUE THREAD

**Issue by geumu** [BentoBoxWorld/MagicCobblestoneGenerator#12]
**bukkit: paperspigot 1.13.2**

I would like to add the function to generate ore when water and fence meet. I hope this works with MagicCobblestoneGenerator.

Lava deletes the item, but fence does not delete the item, so I hope this method exists.

fence_generater: true

**Reference material**
https://cdn.discordapp.com/attachments/588713186036023296/589210457299222548/unknown.png
https://www.spigotmc.org/resources/oregen3-water-block-information-gui-permission-priorities-1-8-1-9-1-10-1-11-1-12-1-13.59598/

**Comment by geumu** [comment]
> Um, I don't understand. Why should water + fence generate ore? It doesn't make sense to me.

hi tastybento. I'm from South Korea. Some servers in Korea use the fence + water method.

The reasons are as follows.
lava removes the item and occasionally lets the user die, so I created an ore when another block and water meet instead of lava to lower the user's entry barrier.

There are about 700 servers in Korea, and the majority of servers are skyblocks. This feature does not exist at 1.13.2, and users and servers are embarrassed. I hope it gets updated. thank you.

**Comment by nzminecraftDOTcom** [comment]
Isn't that the whole point of a Cobblestone Generator? You run the risk of items burning or you dying?
Why not use a piston to push blocks out of the way so they don't burn.

**Comment by Banbeucmas** [comment]
> Isn't that the whole point of a Cobblestone Generator? You run the risk of items burning or you dying?
> Why not use a piston to push blocks out of the way so they don't burn.

For gameplay stuff, servers love those flashy. This is the same with the Vietnamese community

**Comment by geumu** [comment]
> > Cobblestone Generator의 핵심은 아닌가? 당신은 아이템이 타거나 당신이 죽을 위험을 감수하고 있습니까? 
> > 블록을 밀어내어 타지 않도록 피스톤을 사용하지 않는 것이 좋습니다.
> 
> 게임 플레이의 경우, 서버는 화려한 것을 좋아합니다. 이것은 베트남 공동체와 동일합니다.

**Comment by geumu** [comment]
> > Isn't that the whole point of a Cobblestone Generator? You run the risk of items burning or you dying?
> > Why not use a piston to push blocks out of the way so they don't burn.
> 
> For gameplay stuff, servers love those flashy. This is the same with the Vietnamese community

yeah i agree

**Comment by BONNe** [comment]
It was great in 1.12, but it would be weird in 1.13+.

As you know, or not, fences now are waterlogged. Water can be filled inside fence. It will be tricky to do the same in 1.13+ as in 1.12 just because of this feature.

Im not against easier cobble stone generation, just mark that it would be weird functionality after Aquatic Update.

**Comment by BONNe** [comment]
Will not implement.
Mojang provides a better solution for lava and ice.
Yes, lava is still involved, but fences would be weird anyway.
