### ISSUE TITLE
Allow non-players to generate.

### ISSUE THREAD

**Issue by danvei233** [BentoBoxWorld/MagicCobblestoneGenerator#127]
### Is your feature request related to a problem?

The stone genmachine can only generate other blocks when the player digs, and the interaction such as piston will generate stones, hoping to allow unmanned operation to generate them.

### Describe the solution you'd like.

如上

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by muuuioi** [comment]
+1

**Comment by BONNe** [comment]
This is not how Magic Cobblestone Generator operates.
Addon does not care who breaks blocks at all. The only thing it cares is which generators are active on the island. How blocks are removed from a spot does not matter.

![2024-01-11_13 04 19](https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/assets/1344358/b599d00e-90b4-4722-bf63-a26f21c3c2a2)
