### ISSUE TITLE
Biome specific generator results

### ISSUE THREAD

**Issue by darkstrayer** [BentoBoxWorld/MagicCobblestoneGenerator#16]
#### Is your feature request related to a problem?

Different block types are better mined with specific tools, ie. sand and dirt with shovel VS ores with a pickaxe, therefore sand, gravel & dirt produced in the same generator as cobble and ores requires the player to switch tools to remain efficient where server owners permit AFK mining.  
#### Describe the solution you'd like us to implement.

Being able to specify a biome [list] against a generators output results in the settings would allow a player to build shovel compatible generator in the desert/beach/ocean and a pickaxe compatible generator in other biomes. This also creates broader flexibility for server owners to create biome specific outputs.
Light level or block depth range could be an additional settings, allowing various ore results to increase in darkness or lower block levels.
#### Describe alternatives you've considered.

Players just deal with the durability loss and slower mining speeds. 
#### Additional context

Could this also fulfil the requests for generators in other dimensions?

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.

As it would be very hard to define a different output from biome in the same generator, I decided to add required biome for a generator to work.
f.e.
You can specify that the generator works only in the Swamp biome, so it will not work in other biomes.
This allowed also to get rid of environment-specific generators, as it can be done with biomes. By specifying that the generator should work only in NETHER_WASTE or other nether biomes, it is possible to limit its output only in the nether. 
The same could be done for end world.
