### ISSUE TITLE
generator per  world

### ISSUE THREAD

**Issue by thunderlight411** [BentoBoxWorld/MagicCobblestoneGenerator#17]
### Description
I like to see a CobbleGenerator depending on the world you are in.

#### Describe the solution you'd like us to implement.
Like to have some kind or stone / ores depending on the world the generator is made of.
for exemple if you make a generator in the nether you have some changes to gain soul_sand nether_quartz_ore and netherrack

and for the end some end_stone.
now we have to put all the items in 1 generator what makes it realy complex to give some persentage of change to gain some kind of blocks

**Comment by elhertz** [comment]
I don't know about the nether  but I definitely want to get end stone from the end.

**Comment by SirvydasS** [comment]
it will be awesome

**Comment by Espantonius** [comment]
The same thing i have asked in discord.
It would be nice if it could be added per world because it would create more gameplay. This way you can modify the blocks so that users have to go to the other worlds to get other blocks.

**Comment by BONNe** [comment]
The implementation will be created per Biome.
In general, this will allow even more customization then only checking different environments.
