### ISSUE TITLE
Permission tiers

### ISSUE THREAD

**Issue by AmazedMender16** [BentoBoxWorld/MagicCobblestoneGenerator#18]
#### Is your feature request related to a problem?

I like to see permission based tiers aswell, for example you need x level and permissions x.

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.

**Comment by AmazedMender16** [comment]
Hi @BONNe how was this exactly implemented? I meant like:
If user has generator.1 it will have generator 1 blocks, if other user has generator.2 then it will get generator 2 blocks.

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator#generatortemplateyml

**Comment by AmazedMender16** [comment]
@BONNe looks like that won’t automatically enable that generator? It allows user to select, I don’t want the user to interact, the permission should be the one controlling it. If that possible in current implementation?

**Comment by BONNe** [comment]
No, it is not possible in current implementation.

This addon is based on user input.
