### ISSUE TITLE
Magic cobblegen on other worlds

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/MagicCobblestoneGenerator#2]
_From @tastybento on July 15, 2017 22:18_

_From @BirkhoffLee on May 17, 2017 11:24_

Hey there! Currently, the magic cobblegen only works on the skyblock world. However what do you think of supporting it on other worlds like spawn too?

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#226_

_Copied from original issue: BentoBoxWorld/bentobox#66_

**Comment by Awakened-Redstone** [comment]
I can do that to.
With configs.
