### ISSUE TITLE
Stone generate problem

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#20]
### Description
I can't make a NORMAL stone generator. Look this:

![image](https://user-images.githubusercontent.com/47111280/64921536-36d97800-d7cd-11e9-87f0-2df69d76923c.png)

#### Server / BentoBox information:

![image](https://user-images.githubusercontent.com/47111280/64921518-f843bd80-d7cc-11e9-94c1-2c9b57c1646d.png)

 
![image](https://user-images.githubusercontent.com/47111280/64921515-efeb8280-d7cc-11e9-923d-fffb1f33c055.png)

**Comment by BONNe** [comment]
That is not a bug.
There is a plan to create an increased rate "magic" if the stone generator is used.
But no ETA.
