### ISSUE TITLE
Decimal support

### ISSUE THREAD

**Issue by Hackuou** [BentoBoxWorld/MagicCobblestoneGenerator#21]
#### Describe the solution you'd like us to implement.

Support for decimals in the block probabilities. (Might be good to inform people that probabilities don't have to add to 100 and give some examples of with decimals and without, so people better know how the addon works).

#### Describe alternatives you've considered.

I know you can set higher numbers as the percentages don't have to add to 100 but makes it easier for people configuring this addon for the first time as it's how other addons work

**Comment by BONNe** [comment]
Will not implement.

**Comment by tastybento** [comment]
Related to #27
