### ISSUE TITLE
Water not flowing

### ISSUE THREAD

**Issue by ScuroK** [BentoBoxWorld/MagicCobblestoneGenerator#24]
The water does often not flow when building the generator for the first time. I needs a manual block update to make it flow. Often a stone block gets generated too early. maybe this is the cause?

this can be very confusing for normal players. 

could you fix this?

**Comment by BONNe** [comment]
Can you show it with an image or video? 

I cannot reproduce this with a generator, that I am using.

**Comment by tastybento** [comment]
@ScuroK Where are you building the generator? There is a setting that prevents water flow outside of island protection areas so if you're in an unowned location (do `/bsb info`) then this might be what is happening.

**Comment by ScuroK** [comment]
![2019-10-10_16 26 55](https://user-images.githubusercontent.com/10480144/66578160-e0b4e600-eb7a-11e9-9814-2a53f0980ba5.png)

**Comment by tastybento** [comment]
@ScuroK please answer my questions - looks like I wrote...

**Comment by ScuroK** [comment]
@tastybento on my own island

**Comment by BONNe** [comment]
I got it... 
Yea.. water must always go before lava :D
I will fix it
