### ISSUE TITLE
Rates below 1% indicate 0%.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#27]
#### Describe the bug
I want it to show rates below 1% properly.

>   tier3:
    min-level: 200
    name: "Enchant zamanı!"
    blocks:
      IRON_ORE: 5
      DIORITE: 10
      GRANITE: 10
      ANDESITE: 10
      COBBLESTONE: 1000
      COAL_ORE: 20
      GOLD_ORE: 5
      LAPIS_ORE: 2

#### Screenshots and videos
![image](https://user-images.githubusercontent.com/47111280/68388892-b4d55200-0172-11ea-960d-4c40fa7992bd.png)

#### Server
 - OS: **Centos 7**
 - Java version: **8**

**Comment by tastybento** [comment]
![Screen Shot 2019-11-07 at 11 59 30 AM](https://user-images.githubusercontent.com/4407265/68422987-19ce7f00-0156-11ea-8b94-2bb8790b2880.png)
:-)
I think up to 2 decimal places!

**Comment by tastybento** [comment]
![Screen Shot 2019-11-07 at 12 11 52 PM](https://user-images.githubusercontent.com/4407265/68423952-e0970e80-0157-11ea-8d4c-42e747ece5f4.png)
Much better...
