### ISSUE TITLE
Make MagicOreGen can work with both island levels and permissions

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/MagicCobblestoneGenerator#3]
_From @tastybento on July 15, 2017 22:13_

_From @Poslovitch on March 29, 2017 18:39_

_From @Poslovitch on December 12, 2016 14:52_

https://www.spigotmc.org/threads/a-skyblock.30325/page-155#post-2082177

It should be quite hard to do... 

_Copied from original issue: tastybento/askyblock#399_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#44_

_Copied from original issue: BentoBoxWorld/bentobox#50_

**Comment by Poslovitch** [comment]
Thought of a way to do that (which would be also applicable to #40).

![yaml](https://puu.sh/wTrip/9f7e813de5.png)

**Comment by Poslovitch** [comment]
_From @tastybento on July 26, 2017 14:59_

The condition is interesting. Make sure that if you are going to teach admins a new language, like this condition scripting, that you have room for expansion and that you use it consistently across all similar situations. i.e., this cannot be only for Magic Cobble, but elsewhere another condition system is used. Also, that will help in the programming - just have one parser. 
So, one place it could be used is in Challenges for example. Also, consider how to do more complex conditions. Like (level>500 AND level<1000) OR money > 3000;
Maybe the Java [ScriptEngine](http://docs.oracle.com/javase/6/docs/api/javax/script/ScriptEngine.html) could be used to evaluate the string?

**Comment by Poslovitch** [comment]
Sure, this system would be used notably for Magic Cobble Generator, for #40, and maybe for challenges (though i'm not completely sure for this one).

We would also be able to make the more complex conditions you suggested ^^

ScriptEngine looks good. However, i'll have to do some experiments with it ^^

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.
