### ISSUE TITLE
Add Placeholders for MagicCobblestoneGenerator

### ISSUE THREAD

**Issue by Ibesh** [BentoBoxWorld/MagicCobblestoneGenerator#30]
**Description**
This placeholder would return which tier cobblestone generator 'your' island has. This would be a usefull feature to have. For example for Upgrade Menu's, information menu's, etc.

**Placeholder**: `%island_generator_tier%` or something similar :)

**Comment by Poslovitch** [comment]
Done.
Implemented as `%MagicCobblestoneGenerator_[gamemode]_island_generator_tier%`.
