### ISSUE TITLE
Some redstone mechanics won't work

### ISSUE THREAD

**Issue by mindw0rm** [BentoBoxWorld/MagicCobblestoneGenerator#33]
#### Describe the bug

I tried building a sinple redstone machine that will push the generated blocks to the side, so that I can break them without risking them burning in the lava.
However, it did not work, because the newly generated block won't transmit the redstone signal of the torch placed below to the block above. 
When the cobblestone generator is disabled (via the settings flag), the machine works. 

#### Steps to reproduce the behavior

Build a redstone machine that depends on conducting the signal through the block generated by the cobblestone generator. See screenshot below for an example. 
The signal won't get transmitted. 
Disable the cobblestone generator via settings: signal will get transmitted. 

#### Expected behavior

The signal should be transmitted through the block. 

#### Screenshots and videos (Optional)

![redstone](https://user-images.githubusercontent.com/6404575/74085405-eebb3a80-4a78-11ea-84b9-06ae7b16b35d.png)
This is a simple machine (this version built in a vanilla world) that won't work with the magic cobblestone generator. 

##### BentoBox Version (Mandatory)

```
Es läuft SPIGOT 1.15.2.
BentoBox-Version: 1.11.0
Datenbank: SQLITE
Geladene Spielewelten:
acidisland_world (AcidIsland): Oberwelt, [nether_color]Nether, [end_color]Ende
bskyblock_world (BSkyBlock): Oberwelt, [nether_color]Nether, [end_color]Ende
caveblock-world (CaveBlock): Oberwelt, [nether_color]Nether, [end_color]Ende
Geladene Addons:
AcidIsland 1.11.0 (ENABLED)
BentoBox-InvSwitcher 1.6.0 (ENABLED)
Biomes 1.6.0.1-SNAPSHOT-b151 (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
CauldronWitchery 1.5.0.0-SNAPSHOT-LOCAL (ENABLED)
CaveBlock 1.11.0 (ENABLED)
Challenges 0.9.0-SNAPSHOT-b398 (ENABLED)
DimensionalTrees 1.6.0-SNAPSHOT-b80 (ENABLED)
Greenhouses 1.0.1-SNAPSHOT-b120 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.0-SNAPSHOT-b17 (ENABLED)
MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b95 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
Warps 1.9.3-SNAPSHOT-b222 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (18): LuckPerms, WorldEdit, AsyncWorldEdit, PlaceholderAPI, UltimateTimber, KidsTimeBoard, Vault, FarmLimiter, BungeeTabListPlus, ProtocolLib, WorldGuard, ChestSort, CoreProtect, TitleManager, BentoBox, Plan, Multiverse-Core, CMI
```
 
### Additional context (Optional)

I modified the code so that physics is used; this will make the machine work. 
I assume you had good reasons to disable physics - even if I am not aware of them - so always using physics might be problematic. So maybe the use of physics should be made optional, so that the server operator can decide which problems should occur? 
I'll make you a pull request for that.

**Comment by tastybento** [comment]
PR merged.
