### ISSUE TITLE
Nether update pending 1.16 release

### ISSUE THREAD

**Issue by johncsuti** [BentoBoxWorld/MagicCobblestoneGenerator#36]
#### Is your feature request related to a problem?

Currently the latest snapshots have different biomes for the nether. This is great for a survival or single player world but it posses an issue for a void nether world.

#### Describe the solution you'd like us to implement.

A current fix for this aside from changing the biome in the nether and filling chunks would be to have a cobble stone generator changing its blocks based on the world it is in such as overworld > cobblestone nether > netherack end > end stone. This would all be set in the config and server owners can change the values.

#### Describe alternatives you've considered.

Changing the biome and fill blocks but that seems to be a worse idea because you can't represent a 3D space in a 2D gui.

### Additional context

None

**Comment by johncsuti** [comment]
The main feature was MGC but this should be implemented before 1.16 is released. I have had lots of players tell me that the nether is not that good compared to the overworld islands.

**Comment by johncsuti** [comment]
Welp 1.16 is out what now?

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.
