### ISSUE TITLE
[Suggestion] Drop treasure at various levels, rarely.

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/MagicCobblestoneGenerator#39]
#### Is your feature request related to a problem?

no - suggestion to add something new and interesting that other skyblock plugins dont have and doesn't require performance sluggy addons for an addon to an addon.. etc.

#### Describe the solution you'd like us to implement.

The ability to set various treasure % chance drop at various levels, so players can work towards level 1000 to have a 1% chance every once in a long while to drop treasure like heart of the sea or a trident, or bee nest or something that's harder to get in skyblock or cave, etc. 

#### Describe alternatives you've considered.

none, i guess write more addons by ppl i dont trust to achieve this, i dont want to do that.

### Additional context

Awesome work on bentobox addons!

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.

The only limitation: As spigot does not provide the ability to mark blocks with data, then treasure will be dropped on block generation.
