### ISSUE TITLE
Magic Cobble Generator doesn't work with auto cobble geneterator.

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/MagicCobblestoneGenerator#4]
_From @tastybento on July 15, 2017 22:7_

_From @Poslovitch on March 29, 2017 18:35_

_From @wasder on January 11, 2017 13:51_

![](http://i.imgur.com/iixfQZD.png)
But if I break the block by hand, it will generate "magic"
![](http://i.imgur.com/FZsQVqR.png)

_Copied from original issue: tastybento/askyblock#455_

_Copied from original issue: tastybento/ASkyBlock-Bugs-N-Features#36_

_Copied from original issue: BentoBoxWorld/bentobox#35_

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:7_

_From @Poslovitch on March 29, 2017 18:35_

_From @krfcm on January 11, 2017 19:21_

This generator also do not work (I break the block by hand) http://screenshot.sh/oB1zsx0GVegoj http://screenshot.sh/n8mcVAFBwnDqP

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:7_

_From @Poslovitch on March 29, 2017 18:35_

_From @tastybento on January 12, 2017 4:48_

Yes, not all generators work. This is a known issue. It may take a while to fix.

**Comment by Poslovitch** [comment]
_From @tastybento on July 15, 2017 22:7_

Here's code for a magic cobble gen that may be something we can use (I received the link off a player and I have not tried it or looked at it)
https://github.com/mastercake10/CustomOreGen

**Comment by Awakened-Redstone** [comment]
I can fix this really easy :D
I think

**Comment by BONNe** [comment]
Implemented. Flag in settings.
