### ISSUE TITLE
1.16 magic basalt generator

### ISSUE THREAD

**Issue by werken23** [BentoBoxWorld/MagicCobblestoneGenerator#49]
#### Is your feature request related to a problem?

-
#### Describe the solution you'd like us to implement.

In the snapshots for the coming 1.16 update they added a way to generate basalt. It would be nice being able to customize what these generators spawn just like the normal magic cobblestone generator.
#### Describe alternatives you've considered.

-
### Additional context

basalt generator: https://minecraft.gamepedia.com/File:Basalt_generator.gif

**Comment by tastybento** [comment]
This should be possible. We'll just need to wait until the 1.16 API is released.

**Comment by BONNe** [comment]
Duplicates #36
Closing.
