### ISSUE TITLE
BSkyBlock Ore Generator

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/MagicCobblestoneGenerator#5]
_From @Methitic on September 16, 2018 12:42_

I would love to have different ore-generators in the nether and the end, that you could be configured differently, just like we had with island levels in ASkyBlock.

Also having different ore-generators, for example based on settings (like biome), would be awesome so you could have an ore-generator for the normal stuff (coal, iron, etc) and one for things like gravel, sand, dirt, etc.

_Copied from original issue: BentoBoxWorld/bentobox#273_

**Comment by Poslovitch** [comment]
I'll move this issue to the appropriate repo.

**Comment by Awakened-Redstone** [comment]
Hmmmm. I can do that to
