### ISSUE TITLE
[Suggestion] Choose the Generator Level

### ISSUE THREAD

**Issue by NemeStorme** [BentoBoxWorld/MagicCobblestoneGenerator#50]
#### Is your feature request related to a problem?
No.

#### Describe the solution you'd like us to implement.

I wish we could choose the level of our generator. For example, I'm at level 100, and I've unlocked a new generator, but this one doesn't suit me. So I would like to go back to the level 25 generator.

We could choose it with a command like /island generator choose [name]

#### Describe alternatives you've considered.
.

**Comment by BONNe** [comment]
Implemented in 2.0.0 version.
Currently in develop branch.
