### ISSUE TITLE
1.16 Basalt generator replace to cobblestone generator

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#52]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/85985038-bd74e400-b9f2-11ea-8973-ba3aaed65b40.png)

How to make basalt generator in 1.16?
https://www.youtube.com/watch?v=q41c3jQtaxo

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/85985073-d382a480-b9f2-11ea-9298-fb0758a307e7.png)

**Comment by BONNe** [comment]
Yes, currently version just overwrites every generator in the world. It includes cobblestone, stone and basalt generators.
Soon, will be published version where admins will be able to specify which generator is overwritten and how it is done. 
No ETA.

**Comment by OverBrave** [comment]
You said there is no specific time, but if you try this hand in this week? Because I'm about to switch my server to 1.16. There are 2-3 things left. And this is someone. I don't want to turn on my server when there are deficiencies.

**Comment by BONNe** [comment]
Well, I am planning to release it in this week, but everything could happen... 

And released version (<2.0) does not target basalt. :)

**Comment by OverBrave** [comment]
Maybe you can disable generator creator in bskyblock_world_nether world

**Comment by BONNe** [comment]
Well, you can just use the older version where the basalt generator is not overwritten.
For 2.0.0 almost everything is finished, just need to finish GUI's, commands and implement into Upgrades. 
Without these things, even if I disable generator in the nether world, it would still be unusable.

**Comment by OverBrave** [comment]
What is this version?

**Comment by OverBrave** [comment]
No need anymore. I can tell players who want to use it to turn off this setting on their island.
![image](https://user-images.githubusercontent.com/47111280/86095768-1445f080-babb-11ea-9472-5d8f63f511ed.png)
