### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#55]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/86536578-73f42f80-bef1-11ea-8ccc-e98fcd5cbf8f.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/86536582-84a4a580-bef1-11ea-80a4-cc018a2c7cb1.png)

**Comment by tastybento** [comment]
I just fixed this. Try build 125. 
#54

**Comment by OverBrave** [comment]
Problem contiunes
![image](https://user-images.githubusercontent.com/47111280/86540196-115c5d00-bf0c-11ea-90a1-33c5fe2283e6.png)
![image](https://user-images.githubusercontent.com/47111280/86540200-1a4d2e80-bf0c-11ea-84de-5dc411526a4e.png)

**Comment by OverBrave** [comment]
Ah wait, version not changed.

**Comment by OverBrave** [comment]
Some jenkins cache problems... Fixed thanks <3
