### ISSUE TITLE
IslandDeleteEvent error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#56]
#### Describe the bug
![image](https://user-images.githubusercontent.com/47111280/86569455-1d313900-bf77-11ea-8440-3495a534f315.png)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/86569487-28846480-bf77-11ea-99ab-a7fe063eb895.png)

**Comment by BONNe** [comment]
@tastybento or @Poslovitch 
I have a question about IslandDeletedEvent. 

Is it possible that event is called without an island or the island already lost its uniqueId?

As code is crashing in part:
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/blob/783344efe60cfe1a2c8410ffcb6692a754467b8d/src/main/java/world/bentobox/magiccobblestonegenerator/listeners/JoinLeaveListener.java#L70

where addon is provided and is not null, the same for the manager and event...
the only null-pointer could happen when the island in the event is set to null.

**Comment by tastybento** [comment]
@BONNe Yes, `IslandDeletedEvent` is called when the island is actually **deleted**, i.e., gone. Therefore Island object is null at that time. You may want to use `IslandDeleteEvent` that still has a valid Island object. This is called after players have been removed though and just the island is left, so there is another event called `IslandPreclearEvent` that is called before anything has been touched. That is often the safest one to use.

**Comment by tastybento** [comment]
By the way, if you do want to get useful info out of `IslandDeletedEvent`, then you need to use the [`getDeletedIslandInfo()` ](https://ci.codemc.io/job/BentoBoxWorld/job/BentoBox/ws/target/apidocs/world/bentobox/bentobox/api/events/island/IslandEvent.IslandDeletedEvent.html) method, which will return the data on the island in an [`IslandDeletion`](https://ci.codemc.io/job/BentoBoxWorld/job/BentoBox/ws/target/apidocs/world/bentobox/bentobox/database/objects/IslandDeletion.html) object.
