### ISSUE TITLE
Database broken

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/MagicCobblestoneGenerator#57]
#### Describe the bug
If I change the database while the server is off, the entire database will disappear on its own and only the default settings will appear.

If I import through the template, the ore rates are listed as ridiculous.

Although I do 1% chance, it seems to be 100% chance. I have database files here. If you want to try:

Can you add generator settings in the game?

And basalt generator not imported.

[bskyblock-generator.zip](https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/files/4880910/bskyblock-generator.zip)

##### Output of `/bbox version` (Mandatory)
![image](https://user-images.githubusercontent.com/47111280/86633759-bdb84500-bfd9-11ea-9caa-361123a0c07a.png)

**Comment by OverBrave** [comment]
Example 
![image](https://user-images.githubusercontent.com/47111280/86635146-67e49c80-bfdb-11ea-8299-699e7cd29649.png)
![image](https://user-images.githubusercontent.com/47111280/86635222-7a5ed600-bfdb-11ea-8206-1ca7e60c92b3.png)

**Comment by OverBrave** [comment]
And if i change database folder when server close, after open the server. Only have 2 generator:
![image](https://user-images.githubusercontent.com/47111280/86635452-c3168f00-bfdb-11ea-8e94-c2711e737879.png)

**Comment by BONNe** [comment]
Ok, I need to improve output message :D
I know I forgot to do something there.

So, in database it stores values from which it will start to generate the object...
Iron Ore -> from 0 .. till 0.5
andesite -> from 5.5 till 8.0
lapis ore -> from 99.8 till 100

I will fix output message to display it correctly :)

**Comment by OverBrave** [comment]
Problem keep contiunes
![image](https://user-images.githubusercontent.com/47111280/86657139-aafd3a80-bff0-11ea-80b5-d95a165b47ff.png)
![image](https://user-images.githubusercontent.com/47111280/86657183-b3ee0c00-bff0-11ea-9fac-ae13226fbde4.png)

![image](https://user-images.githubusercontent.com/47111280/86657165-b05a8500-bff0-11ea-8577-b0cecc8c38a4.png)

**Comment by BONNe** [comment]
It is not a bug. 

If you do not like output of [number] in locale, you can try 
[#.#] - 1 digit after comma
[#.##] - 2 digits after comma
[#.###] - 3 digits after comma
[#.####] - 4 digits after comma
[#.#####] - 5 digits after comma

https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/blob/891e4293425b09e65fd6d293e3329154b76106a9/src/main/resources/locales/en-US.yml#L20:L28
