### ISSUE TITLE
Can't buy a generator

### ISSUE THREAD

**Issue by Momonche** [BentoBoxWorld/MagicCobblestoneGenerator#60]
#### Describe the bug
It's actually impossible to buy a generator
I see on Discord "should have a gold block under the diamond", there is no gold block

#### Steps to reproduce the behavior
/is generator
Right click on a generator

#### Expected behavior
Possibility to buy a generator

##### Output of `/bbox version` (Mandatory)

```
[15:15:54 INFO]: Serveur : PAPER 1.15.2.
[15:15:54 INFO]: Version de BentoBox : 1.14.1-SNAPSHOT-b1835
[15:15:54 INFO]: Database: MARIADB
[15:15:54 INFO]: Mondes de jeu :
[15:15:54 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[15:15:54 INFO]: Addons :
[15:15:54 INFO]: Biomes 1.13.0-SNAPSHOT-b180 (ENABLED)
[15:15:54 INFO]: BSkyBlock 1.14.0 (ENABLED)
[15:15:54 INFO]: Challenges 0.8.4-SNAPSHOT-b428 (ENABLED)
[15:15:54 INFO]: IslandFly 1.8.0 (ENABLED)
[15:15:54 INFO]: Level 2.3.2-SNAPSHOT-b396 (ENABLED)
[15:15:54 INFO]: MagicCobblestoneGenerator 2.1.0-SNAPSHOT-b142 (ENABLED)
[15:15:54 INFO]: Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)

```
AnimatedScoreboard, BentoBox, BetonQuest, Broadcaster, BungeeTabListPlus, ChestCommands, Citizens, ClearLag, CombatLogX, CoreProtect, DeathMessagesPrime, EpicSpawners, Essentials, EssentialsSpawn, F3NPerm, GemsEconomy*, HelpopEra, HolographicDisplays, Hub, IllegalStack, InfiniteAnvil*, InfiniteDispenserX, JSONAPI-RELOADED, KillerMoney*, LiteBans, Lores*, LuckPerms, Multiverse-Core, Multiverse-Portals, NametagEdit*, NoCheatPlus, OpenInv, PearlFix, PlaceholderAPI, PlugMan, ProtocolLib, RubisEra, ShopGUIPlus, SignEdit, SkinsRestorer, Statz, TradePlus, Vault, VentureChat, ViaVersion, VoteBox, WarnBan, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

**Comment by Sylensky** [comment]
I can confirm this issue because it is the same for me. 
Additionally i can't activate a generator tier if my gamemode island is at the certain required level.

**Comment by Sylensky** [comment]
Edit:
its a dumb user issue that i noticed just now... You have to include the Upgrades Addon aswell to make the Cobblestone Generator work properly.
Else you won't see the golden block to buy the upgrade.

**Comment by Momonche** [comment]
Lol
[MagicCobblestoneGenerator] Upgrades add-on not found so Magic Cobblestone Generator, some parts may not work!
I was thinking about an upgrade of MagicCobblestoneGenerator...
Dammit :p

**Comment by Sylensky** [comment]
Are you able to activate the tiers or did i miss something too?
