### ISSUE TITLE
Additional generator type

### ISSUE THREAD

**Issue by Sylensky** [BentoBoxWorld/MagicCobblestoneGenerator#70]
#### Is your feature request related to a problem?

My request is not related to a problem.

#### Describe the solution you'd like us to implement.

As for the 1.16 update the basalt generator type kind of brought me to this idea to have the generators only available in the proper world itself. Like the Cobblestone generator in overworld, the basalt generator in the nether and thats the requesting part, a end generator for the end.
Each of them can only be made in their certain worlds with their configured generations.

#### Describe alternatives you've considered.

I didn't considered an alternative except reusing the stone generator type to make it a nether based one. But a per world generator would be more handy and gives the players an additional challenge.

### Additional context

Nothing to add here.

**Comment by BONNe** [comment]
I will decline this, as this is achievable by abusing biomes. 
You can set a list of biomes where a generator can work, and specify each biome for nether/end or overworld.

Yes, for overworld it would require a lot to specify, but it is possible. 

In the default template there is a nether generator that shows how it can be achievable:

https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/blob/fab649643796933c9fab99d532c83793b9301ac1/src/main/resources/generatorTemplate.yml#L357-L411
