### ISSUE TITLE
Remove Tooltip lines

### ISSUE THREAD

**Issue by fredthedoggy** [BentoBoxWorld/MagicCobblestoneGenerator#79]
#### Is your feature request related to a problem?

Nope, just an enhancement
#### Describe the solution you'd like us to implement.

If you set a line in the language file to be nothing, the line should not be shown.
#### Describe alternatives you've considered.

Remove that part of the tooltip creator, and then re-compile
### Additional context

N/A

**Comment by BONNe** [comment]
Do you want to remove a specific tooltip, or you want to disable them all?

**Comment by fredthedoggy** [comment]
a specific one.  In this case, the biomes but I may decide I want to remove others aswell

**Comment by BONNe** [comment]
You can remove `[biomes]` from the requirements section in locale:
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/blob/develop/src/main/resources/locales/en-US.yml#L782

Or remove `[requirements]` section section from generator description:
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/blob/develop/src/main/resources/locales/en-US.yml#L762

**Comment by fredthedoggy** [comment]
Thank you! That works perfectly!
