### ISSUE TITLE
The generators gets stuck

### ISSUE THREAD

**Issue by DigitalSynware** [BentoBoxWorld/MagicCobblestoneGenerator#84]
### Description
It seems that when the chunks are unloaded the generators stop working (the water does not go into the lava)
This happens when you use Minions plugins to mine the generator blocks. If the minion mines a block and just downloads the chunk, the physics of the fluids are stopped and when it reloads the chunk they are not updated.

I reported it to the creator of the Minions plugin but he says it's the fault of this addon because it doesn't take into consideration other possibilities when the block is mined (the blocks may not be mined by a player)

**IMPORTANT** I tried to do the same bug with this addon disabled and the generator does not stop when the chunk is unloaded

#### Steps to reproduce the behavior
1. Create a stone generator
2. Place a minion to start chopping
3. Move away so that the chunk unloads (it could be that the block does not get mined by the minion so the bug would not work)
4. Go back to the location of the generator and see how it stands

#### Expected behavior
The generator should not get stuck

#### Screenshots and videos (Optional)
![image](https://user-images.githubusercontent.com/26687602/103575944-b0b9d700-4ed2-11eb-9257-0cb7a2f9ea74.png)

##### Output of `/bbox version` (Mandatory)

```
[21:21:11 INFO]: Corriendo PAPER Invalido.
[21:21:11 INFO]: BentoBox version: 1.15.1-SNAPSHOT-LOCAL
[21:21:11 INFO]: Base de datos: MONGODB
[21:21:11 INFO]: Mundos de juego cargados:
[21:21:11 INFO]: main (BSkyBlock): Mundo, Nether, End
[21:21:11 INFO]: Addons cargados:
[21:21:11 INFO]: Biomes 1.13.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: Border 2.0.0 (ENABLED)
[21:21:11 INFO]: BSkyBlock 1.14.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: Challenges 0.8.4-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: ControlPanel 1.7.0 (ENABLED)
[21:21:11 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[21:21:11 INFO]: Level 2.5.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: Likes 2.0.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: Limits 1.15.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: MagicCobblestoneGenerator 2.1.0-SNAPSHOT-LOCAL (ENABLED)
[21:21:11 INFO]: SkyBlock-Enchants-Addon 0.1-LOCAL (ENABLED)
[21:21:11 INFO]: SkyBlock-KOTH-Addon 0.1-LOCAL (ENABLED)
[21:21:11 INFO]: SkyBlock-SellAll-Addon 0.1-LOCAL (ENABLED)
[21:21:11 INFO]: Warps 1.10.0-SNAPSHOT-LOCAL (ENABLED)
```

**Comment by BONNe** [comment]
That is a weird issue. I do not understand exactly how it can happen, as block generation is never canceled.

You can try enabling debug with `/[admin_command] generator why <player>` command and check the report.
Most likely it could be related to `offline-generation` flag. You can change it via ingame GUI or changing a config file.

**Comment by DigitalSynware** [comment]
I activated the debug with the command you gave me and nothing comes out on the console. I've also tried to deactivate the offline generation and it doesn't solve the problem

**Comment by BONNe** [comment]
I think it is an in-game admin command. It should report about each block generation.

**Comment by DigitalSynware** [comment]
> I think it is an in-game admin command. It should report about each block generation.

I'd tried to execute the command from console and with op, nothing appears in chat or console

> Do Minions Work in the non-BentoBox world?

I'll check it tomorrow ;)

**Comment by DigitalSynware** [comment]
> > I think it is an in-game admin command. It should report about each block generation.
> 
> I'd tried to execute the command from console and with op, nothing appears in chat or console
> 
> > Do Minions Work in the non-BentoBox world?
> 
> I'll check it tomorrow ;)

I tested it in a non-BentoBox world. Minions doesn't stop and generators doesn't get stuck

**Comment by BONNe** [comment]
So you have:
- offline-generation = true
- use-physic = true

And it still stuck with the missing block? That is interesting... and that is the reason why I hate Premium plugins, as it is not possible to debug where is the issue.

Technically, MagicCobblestoneGenerator never cancels BlockGenerationEvent. So it should never leave empty space. Empty space can be left only if something suppressed block update after it was removed.

But as I do not know how minions work, it is impossible to help here.

**Comment by BONNe** [comment]
One thing you can try:
Disable MagicCobblestoneGenerator addon completely and check if-then blocks are generated correctly.

**Comment by DigitalSynware** [comment]
> One thing you can try:
> Disable MagicCobblestoneGenerator addon completely and check if-then blocks are generated correctly.

Already tested, blocks are generated correctly and the generators doesn't get stuck.
I will contact the creator of the Minions plugin to see if you can solve this problem. I can't do anything :(

**Comment by BONNe** [comment]
The thing about MCG (also relates to the AOneBlock magic block).

It is processed in the next tick, so technically, if Minion removes the block in the next tick too, it is possible, that block is taken without an update anything...
However, it does not explain, why it does work when a player is near...

Also, do minions keep chunks loaded?

**Comment by BONNe** [comment]
Yapperyapps via discord gave a suggestion that will be implemented.

**Comment by alexeses** [comment]
Great! We'll be waiting, I have that same problem.

**Comment by BONNe** [comment]
I improve block replacement.
It is possible that changes in 2.3.0 are not solving issues with Minions.

**Comment by alexeses** [comment]
Hello!

So it's advisable to wait until you finish the solution to the fault? Or you could try it already?

Thank you!

**Comment by BONNe** [comment]
You can already test it:
https://ci.codemc.io/job/BentoBoxWorld/job/MagicCobblestoneGenerator/

**Comment by BONNe** [comment]
So do recent changes helped with minons, or should there be special handling for them?

**Comment by alexeses** [comment]
Hello!

I've been 2 days with the update of the new generator and I sincerely report a user who is still the same. It tells me that the lava is not flowing properly.

Photo: https://prnt.sc/wkbh8e

As I was saying, I use Tuinity last version with the latest version of all bentobox add-ons

**Comment by DigitalSynware** [comment]
> Hello!
> 
> I've been 2 days with the update of the new generator and I sincerely report a user who is still the same. It tells me that the lava is not flowing properly.
> 
> Photo: https://prnt.sc/wkbh8e
> 
> As I was saying, I use Tuinity last version with the latest version of all bentobox add-ons

Not fixed, the issue is still ocurring. It's happening the same issue as @alexeses

**Comment by BONNe** [comment]
I could not reproduce this issue. I tried with different configurations and could not get it in this position.
Does it happen frequently, or is it something rare?
Could you please provide the coordinate of the generator (lava + empty space)?

**Comment by BONNe** [comment]
So, no one could provide the location of the lava+stucked block?

I tested it with a lot of different configurations and could not get a stuck generator.

**Comment by alexeses** [comment]
Hello!

I'm very sorry for the delay in responding, apparently the problem has been solved and no user has reported it to me again. 

Thanks for all the support, it has been very helpful! +5 stars ^^
