### ISSUE TITLE
Error : NULL 

### ISSUE THREAD

**Issue by n54b** [BentoBoxWorld/MagicCobblestoneGenerator#85]
I have this problem with 2 players from the same island!
When they make /is generator ... 
Any idea ?

```
06.01 18:51:27 [Server] Server thread/ERROR null
06.01 18:51:27 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'is generator' in world.bentobox.bskyblock.BSkyBlock$1(island)
06.01 18:51:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
06.01 18:51:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
06.01 18:51:27 [Server] INFO Caused by: java.lang.NullPointerException
06.01 18:51:27 [Server] INFO at world.bentobox.bentobox.api.user.User.hasPermission(User.java:242) ~[?:?]
06.01 18:51:27 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
06.01 18:51:27 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_111]
06.01 18:51:30 [Multicraft] Skipped 25 lines due to rate limit (30/s)

**Comment by n54b** [comment]
![image](https://user-images.githubusercontent.com/12047619/103802438-6ad64d80-504f-11eb-874c-f71562e01011.png)

**Comment by BONNe** [comment]
I think the error comes from the older BentoBox version.

MCG 2.2 is built on BentoBox 1.15.4

**Comment by n54b** [comment]
sorry for the delay of answer all is good :)

**Comment by n54b** [comment]
23.02 10:41:29 [Server] Server thread/ERROR null
23.02 10:41:29 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'is generator' in world.bentobox.bskyblock.BSkyBlock$1(island)
23.02 10:41:29 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
23.02 10:41:29 [Server] INFO Caused by: java.lang.NullPointerException

this error is back :(

23.02 10:43:08 [Server] Server thread/INFO Serveur Invalide () Invalide.
23.02 10:43:08 [Server] Server thread/INFO Version de BentoBox : 1.16.0-SNAPSHOT-b1947
23.02 10:43:08 [Server] Server thread/INFO Base de données : JSON
23.02 10:43:08 [Server] Server thread/INFO Mondes de jeu chargés :
23.02 10:43:08 [Server] Server thread/INFO bskyblock_world (BSkyBlock) : Overworld
23.02 10:43:08 [Server] Server thread/INFO Addons chargés :
23.02 10:43:08 [Server] Server thread/INFO Biomes 1.14.0-SNAPSHOT-b198 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Border 2.0.2-SNAPSHOT-b72 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO BSkyBlock 1.14.3 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Chat 1.1.2-SNAPSHOT-b42 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO ControlPanel 1.13.0-SNAPSHOT-b45 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Level 2.5.2 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Likes 2.1.1-SNAPSHOT-b43 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Limits 1.15.2 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO MagicCobblestoneGenerator 2.3.0-SNAPSHOT-b204 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Warps 1.11.0-SNAPSHOT-b279 (ENABLED)

Spigot 1.16.5

the player is co-owner and has the right to open the generator but the island manager is not connected ...

**Comment by n54b** [comment]
Duplicate of ticket ^^
