### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by n54b** [BentoBoxWorld/MagicCobblestoneGenerator#87]
Some player have this error when he use /is generator

```28.01 15:07:23 [Server] Server thread/ERROR null
28.01 15:07:23 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'is generator' in world.bentobox.bskyblock.BSkyBlock$1(island)
28.01 15:07:23 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:758) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
28.01 15:07:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
28.01 15:07:23 [Server] INFO Caused by: java.lang.NullPointerException
28.01 15:07:23 [Server] INFO at world.bentobox.bentobox.api.user.User.hasPermission(User.java:245) ~[?:?]
28.01 15:07:23 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
28.01 15:07:23 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_111]

**Comment by BONNe** [comment]
Can you provide output of:
/bentobox version

**Comment by n54b** [comment]
28.01 20:29:11 [Server] Server thread/INFO Serveur SPIGOT 1.16.3.
28.01 20:29:11 [Server] Server thread/INFO Version de BentoBox : 1.16.0-SNAPSHOT-b1947
28.01 20:29:11 [Server] Server thread/INFO Base de données : JSON
28.01 20:29:11 [Server] Server thread/INFO Mondes de jeu chargés :
28.01 20:29:11 [Server] Server thread/INFO bskyblock_world (BSkyBlock) : Overworld
28.01 20:29:11 [Server] Server thread/INFO Addons chargés :
28.01 20:29:11 [Server] Server thread/INFO Biomes 1.14.0-SNAPSHOT-b198 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Border 2.0.2-SNAPSHOT-b72 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO BSkyBlock 1.14.3 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Chat 1.1.2-SNAPSHOT-b42 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO ControlPanel 1.13.0-SNAPSHOT-b45 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Level 2.5.1 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Likes 2.1.0-SNAPSHOT-b39 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Limits 1.15.2 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO MagicCobblestoneGenerator 2.3.0-SNAPSHOT-b202 (ENABLED)
28.01 20:29:11 [Server] Server thread/INFO Warps 1.11.0-SNAPSHOT-b279 (ENABLED)

**Comment by BONNe** [comment]
@tastybento 
Do you have any idea why User#hasPermission dies with null-pointer?

I cannot find why it could happen.

**Comment by tastybento** [comment]
No, I can't find a reason why either. It can only be caused by `sender` being `null` and that can only happen if the command executer is not a player or not online.

@n54b Who is executing the command? Are you using a menu plugin to run the command or something? Is the player typing `/is generator` manually? Can you share the log before that error?

**Comment by n54b** [comment]
sorry for the delay ^^
some error of the same player :
https://pastebin.com/5Kcwkv0b

typing /is generator manually,
and 
nothing in log :( 

But now the player have NO error ... i think when the server restart its ok ^^

**Comment by BONNe** [comment]
Are you the owner of this island?
Has the island has an owner?

**Comment by n54b** [comment]
i'm not the owner et yes island have a owner ^^

**Comment by BONNe** [comment]
Does the island owner has been in-game?

**Comment by n54b** [comment]
island owner has not online at this moment and no error now ^^

**Comment by n54b** [comment]
23.02 10:41:29 [Server] Server thread/ERROR null
23.02 10:41:29 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'is generator' in world.bentobox.bskyblock.BSkyBlock$1(island)
23.02 10:41:29 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:2991-Spigot-018b9a0-f3f3094]
23.02 10:41:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
23.02 10:41:29 [Server] INFO Caused by: java.lang.NullPointerException

this error is back :(

23.02 10:43:08 [Server] Server thread/INFO Serveur Invalide () Invalide.
23.02 10:43:08 [Server] Server thread/INFO Version de BentoBox : 1.16.0-SNAPSHOT-b1947
23.02 10:43:08 [Server] Server thread/INFO Base de données : JSON
23.02 10:43:08 [Server] Server thread/INFO Mondes de jeu chargés :
23.02 10:43:08 [Server] Server thread/INFO bskyblock_world (BSkyBlock) : Overworld
23.02 10:43:08 [Server] Server thread/INFO Addons chargés :
23.02 10:43:08 [Server] Server thread/INFO Biomes 1.14.0-SNAPSHOT-b198 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Border 2.0.2-SNAPSHOT-b72 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO BSkyBlock 1.14.3 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Chat 1.1.2-SNAPSHOT-b42 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO ControlPanel 1.13.0-SNAPSHOT-b45 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Level 2.5.2 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Likes 2.1.1-SNAPSHOT-b43 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Limits 1.15.2 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO MagicCobblestoneGenerator 2.3.0-SNAPSHOT-b204 (ENABLED)
23.02 10:43:08 [Server] Server thread/INFO Warps 1.11.0-SNAPSHOT-b279 (ENABLED)

Spigot 1.16.5

the player is co-owner and has the right to open the generator but the island owner is not connected ...

**Comment by BONNe** [comment]
Could you show the full bug report, as this is just a command execution error?

**Comment by n54b** [comment]
https://pastebin.com/Zn5zkQ1J

Full error :)

**Comment by BONNe** [comment]
Ok, I think I got why the error is happening. 

@tastybento User#hasPermission need to add a check for sender is not null. As User instance can be created for offline user who does not have sender!

There will be a fix in MCG too, to avoid calling permission check on offine player.
