### ISSUE TITLE
Use island bank/balance to buy generators

### ISSUE THREAD

**Issue by Virologicbody** [BentoBoxWorld/MagicCobblestoneGenerator#94]
#### Is your feature request related to a problem?

Not really a 'problem' but more inconvenient.
Currently a players economy can be used to 'pool'/create an island balance which doesn't seem to get used to anything.

#### Describe the solution you'd like us to implement.

Ability to use the islands balance to buy generators.
The plugin could automatically check for an island balance first and use that balance if it is available before deducting the funds from a players personal balance.

#### Describe alternatives you've considered.

None

### Additional context

None

**Comment by BONNe** [comment]
Implemented with https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/commit/350b5ebd8b0149d74879b0cd1e2ffb8da3b5e505
