### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Tobahodimu** [BentoBoxWorld/MagicCobblestoneGenerator#95]
I install the .jar file as it should in the "addons" folder and when I restart the server the addons is not executed and even if I reload the plugin, it doesn't change anything.

If you know how to help me I would be completely grateful!

**Comment by BONNe** [comment]
Could you share output of:
`/bentobox version` command

**Comment by Tobahodimu** [comment]
[image: image.png]

**Comment by Tobahodimu** [comment]
![paper](https://user-images.githubusercontent.com/42589561/111884406-ce6ee680-89c1-11eb-88bb-e97b35c14bb7.png)

**Comment by BONNe** [comment]
The latest Magic Cobblestone Generator addon requires BentoBox 1.15.4 version.

**Comment by Tobahodimu** [comment]
Le problème étant que je ne trouve pas cette version du plugin, vous avez
un lien qui pourrait m'aider s'il vous plaît?

**Comment by BONNe** [comment]
There are several:

https://download.bentobox.world -> official download packages
https://github.com/BentoBoxWorld/BentoBox/releases -> BentoBox releases
https://ci.codemc.io/job/BentoBoxWorld/job/BentoBox/ -> snapshot (dev) versions

**Comment by Tobahodimu** [comment]
Thank you very much, I just have one last question! Would it be possible to impose a percentage of generations depending on the island level?

**Comment by BONNe** [comment]
Currently no, you can create a different generator that requires larger island level. 

However, if that is not what you want, you can create a new feature request for function, and explain how it should work.
